-- Generated by matugen. Do not edit by hand.
return {
	fg = "{{ base16.base05.default.hex }}",
	red = "{{ base16.base08.default.hex }}",
	orange = "{{ base16.base09.default.hex }}",
	yellow = "{{ base16.base0a.default.hex }}",
	green = "{{ base16.base0b.default.hex }}",
	aqua = "{{ base16.base0c.default.hex }}",
	blue = "{{ base16.base0d.default.hex }}",
	purple = "{{ base16.base0e.default.hex }}",

	-- diff line backgrounds (DiffAdd / DiffDelete)
	bg_green = "{{ colors.primary_container.default.hex }}",
	bg_red = "{{ colors.error_container.default.hex }}",
}
