-- Generated by matugen. Do not edit by hand.
return {
	fg = "{{ base16.base05.default.hex }}",
	red = "{{ base16.base08.default.hex }}",
	orange = "{{ base16.base09.default.hex }}",
	yellow = "{{ base16.base0a.default.hex }}",
	green = "{{ base16.base0b.default.hex }}",
	aqua = "{{ base16.base0c.default.hex }}",
	blue = "{{ base16.base0d.default.hex }}",
	purple = "{{ base16.base0e.default.hex }}",

	-- hue-tinted backgrounds (diff lines, inline highlights, etc.)
	bg_red = "{{ bg.red.default.hex }}",
	bg_orange = "{{ bg.orange.default.hex }}",
	bg_yellow = "{{ bg.yellow.default.hex }}",
	bg_green = "{{ bg.green.default.hex }}",
	bg_cyan = "{{ bg.cyan.default.hex }}",
	bg_blue = "{{ bg.blue.default.hex }}",
	bg_purple = "{{ bg.purple.default.hex }}",
	bg_brown = "{{ bg.brown.default.hex }}",
}
