-- Generated by matugen. Do not edit by hand.
return {
	-- accents
	fg = "{{ base16.base05.default.hex }}",
	red = "{{ base16.base08.default.hex }}",
	orange = "{{ base16.base09.default.hex }}",
	yellow = "{{ base16.base0a.default.hex }}",
	green = "{{ base16.base0b.default.hex }}",
	aqua = "{{ base16.base0c.default.hex }}",
	blue = "{{ base16.base0d.default.hex }}",
	purple = "{{ base16.base0e.default.hex }}",

	-- statusline
	statusline1 = "{{ base16.base0b.default.hex }}",
	statusline2 = "{{ base16.base05.default.hex }}",
	statusline3 = "{{ base16.base08.default.hex }}",

	-- neutral backgrounds (dark -> light)
	bg_dim = "{{ colors.background.default.hex }}",
	bg0 = "{{ base16.base00.default.hex }}",
	bg1 = "{{ base16.base01.default.hex }}",
	bg2 = "{{ base16.base02.default.hex }}",
	bg3 = "{{ base16.base03.default.hex }}",
	bg4 = "{{ base16.base04.default.hex }}",
	bg5 = "{{ colors.outline.default.hex }}",

	-- hue-tinted backgrounds (diff lines, inline highlights, visual selection)
	bg_visual = "{{ colors.error_container.default.hex }}",
	bg_red = "{{ bg.red.default.hex }}",
	bg_green = "{{ bg.green.default.hex }}",
	bg_blue = "{{ bg.blue.default.hex }}",
	bg_yellow = "{{ bg.yellow.default.hex }}",
	bg_purple = "{{ bg.purple.default.hex }}",
}
