[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "7749958"
hash = "26db011a778f261d730d4f5f8bf24b3f"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "7749958"
hash = "f0c8c378184d5f8abd1b095a443d336d"

[[plugin.deps]]
use = "dedukun/bookmarks"
rev = "9ef1254"
hash = "92fbb5483657fa7976cdf4e0104e18e0"

[[plugin.deps]]
use = "larry-oates/open-git-remote"
rev = "72158d6"
hash = "ed359abc14ba915a12e759435ed721ab"

[[plugin.deps]]
use = "XYenon/clipboard"
rev = "0f4982a"
hash = "dcda5f179482ee8cc191ad679c9d72e0"

[flavor]
deps = []
