[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "6229767"
hash = "347cc6b190eb0c2fd60513cc7ae37412"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "6229767"
hash = "87472b05a8c420100f6a2b9cde1e7746"

[[plugin.deps]]
use = "dedukun/bookmarks"
rev = "9ef1254"
hash = "92fbb5483657fa7976cdf4e0104e18e0"

[[plugin.deps]]
use = "larry-oates/open-git-remote"
rev = "72158d6"
hash = "ed359abc14ba915a12e759435ed721ab"

[[plugin.deps]]
use = "XYenon/clipboard"
rev = "a2655fd"
hash = "90625fa33e3372073d60f124c3c867"

[flavor]
deps = []
