# see ui.conf for tmux-cpu settings
set -g @plugin 'tmux-plugins/tmux-cpu'

# tmux-fzf
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="C-h"
TMUX_FZF_OPTIONS="-p -w 60% -h 40% -m --wrap word"

# tmux-resurrect
set -g @resurrect-capture-pane-contents 'on'
## https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md
set -g @resurrect-processes '\
      "gh dash" \
      lazygit \
      paseo \
      yazi \
      "~opencode->opencode --continue" \
      "~nvim->nvim *" \
      "~bend->bend *" \
'
set -g @plugin 'tmux-plugins/tmux-resurrect' 

# tmux-continuum - automatically saves sessions for you every 15 minutes; auto restore when tmux starts
set -g @continuum-restore 'on'
set -g @plugin 'tmux-plugins/tmux-continuum' 

# tmux-yank
set -g @plugin 'tmux-plugins/tmux-yank'

# tmux-flash - copy-mode 🡒 `s` to start flash search
set -g @plugin 'AndreVicencio/tmux-flash'

# tmux-fzf-links
set-option -g @fzf-links-key 'u'
set-option -g @fzf-links-path-extension "$HOME/.config/tmux/scripts/sanitize-capture-pane"
set-option -g @fzf-links-editor-open-cmd "tmux new-window $EDITOR +%line '%file'"
set-option -g @fzf-links-fzf-display-options \
      "-w 60% -h 40% --maxnum-displayed 20 --multi --track --no-preview \
       --header '[󰌑] open [^d] open in default program [^r] reveal in explorer [^c] copy'"
set -g @plugin 'alberti42/tmux-fzf-links'

# Initialize TMUX plugin manager (keep the run line at the very bottom of tmux.conf)
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'

