theme = "base16_transparent"

# -- Editor settings

[editor]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = false

[editor.statusline]
right = ["diagnostics", "selections", "position","position-percentage", "file-encoding"]

# --  Key bindings

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
"^" = "goto_first_nonwhitespace"
"%" = "match_brackets"
H = "goto_line_start"
L = "goto_line_end"
G = "goto_file_end"
C = ["extend_to_line_end", "yank", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank", "delete_selection"]

Y = ["extend_to_line_end", "yank"]
V = ["select_mode", "extend_line"]
S = "surround_add"
x = "delete_selection"

# Center when jumping half page up/down 
C-u = ["page_cursor_half_up", "align_view_center"]
C-d = ["page_cursor_half_down", "align_view_center"]

# Navigate splits
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

# Make j and k behave as they do Vim when soft-wrap is enabled
j = "move_line_down"
k = "move_line_up"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."C-w"]
R = ":config-reload" # reload config

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
esc = ["collapse_selection", "normal_mode"]
C-space = "completion"

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
"^" = "goto_first_nonwhitespace"
"%" = "match_brackets"
H = "goto_line_start"
L = "goto_line_end"
G = "goto_file_end"
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]

u = ["switch_to_lowercase", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"

# Some extra binds to allow us to insert/append in select mode because it's nice with multiple cursors
tab = ["insert_mode", "collapse_selection"] # tab is read by most terminal editors as "C-i"
C-a = ["append_mode", "collapse_selection"]

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

d = ["yank", "delete_selection"]
x = ["yank", "delete_selection"]
y = ["yank", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank", "goto_line_start", "collapse_selection", "normal_mode"]

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
