# yaml-language-server: $schema=https://gh-dash.dev/schema.json

prSections:
  - title: My Pull Requests
    filters: author:@me is:open
  - title: Needs My Review
    filters: review-requested:@me is:open
  - title: Involved
    filters: -author:@me involves:@me is:open
  - title: All (recent 2 weeks)
    filters: is:open updated:>={{ nowModify "-2w" }}

issuesSections:
  - title: My Issues
    filters: author:@me is:open
  - title: Assigned
    filters: assignee:@me is:open
  - title: Involved
    filters: involves:@me -author:@me is:open

notificationsSections:
  - title: All
    filters: ""
  - title: Created
    filters: reason:author
  - title: Participating
    filters: reason:participating
  - title: Mentioned
    filters: reason:mention
  - title: Review Requested
    filters: reason:review-requested
  - title: Assigned
    filters: reason:assign
  - title: Subscribed
    filters: reason:subscribed
  - title: Team Mentioned
    filters: reason:team-mention

repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60

defaults:
  preview:
    open: true
    width: 0.45
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  notificationsLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30

keybindings:
  prs:
    - key: "ctrl+r"
      name: Request review
      command: gh pr edit {{.PrNumber}} --add-reviewer $(gh pr view {{.PrNumber}} --json reviews --jq '[.reviews[].author.login] | unique | join(",")')
    - key: C
      name: code review
      command: >
        nvim -c ':lua Snacks.picker.gh_diff({ repo = "{{.RepoName}}", pr = "{{.PrNumber}}", focus = "list", on_close = function() vim.cmd("qa") end})'
    - key: "d"
      name: "view (nvim)"
      command: nvim -c "autocmd User CodeDiffClose qa" -c ":CodeDiff origin/{{.BaseRefName}} origin/{{.HeadRefName}}"
    - key: T
      name: github actions | enhance
      command: ENHANCE_THEME=overnight_slumber gh enhance -R {{.RepoName}} {{.PrNumber}}
  universal:
    - key: g
      name: lazygit
      command: cd {{.RepoPath}} && echo {{.RepoPath}} && lazygit
    - key: "ctrl+f"
      builtin: pageDown
    - key: "ctrl+b"
      builtin: pageUp

theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: false # horizontal line separating each item in table
      compact: false # compact table rows
  colors:
    text:
      primary: "#d3c6aa"
      secondary: "#83c092"
      inverted: "#2b3339"
      faint: "#7393b3"
      warning: "#dbbc7f"
      success: "#83c092"
      error: "#e67e80"
      actor: "#7fbbb3"
    background:
      selected: "#2E383C"
    border:
      primary: "#2E383C"
      secondary: "#4e565c"
      faint: "#2E383C"

pager:
  diff: ""

confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
includeReadNotifications: true
