-- Generated by matugen. Do not edit by hand.
return {
	fg = "#d3c6aa",
	red = "#e67e80",
	orange = "#e69875",
	yellow = "#dbbc7f",
	green = "#83c092",
	aqua = "#95d1c9",
	blue = "#7393b3",
	purple = "#d699b6",

	-- diff line backgrounds (DiffAdd / DiffDelete)
	bg_green = "#20303b",
	bg_red = "#37222c",
}
