-- Generated by matugen. Do not edit by hand.
return {
	fg = "#d3c6aa",
	red = "#e67e80",
	orange = "#e69875",
	yellow = "#dbbc7f",
	green = "#83c092",
	aqua = "#95d1c9",
	blue = "#7393b3",
	purple = "#d699b6",

	-- hue-tinted backgrounds (diff lines, inline highlights, etc.)
	bg_red = "#452132",
	bg_orange = "#452f21",
	bg_yellow = "#453a21",
	bg_green = "#213c45",
	bg_cyan = "#2e5960",
	bg_blue = "#212d45",
	bg_purple = "#3e2145",
	bg_brown = "#342519",
}
