-- Generated by matugen. Do not edit by hand.
return {
	-- accents
	fg = "#d3c6aa",
	red = "#e67e80",
	orange = "#e69875",
	yellow = "#dbbc7f",
	green = "#83c092",
	aqua = "#95d1c9",
	blue = "#7393b3",
	purple = "#d699b6",

	-- statusline
	statusline1 = "#83c092",
	statusline2 = "#d3c6aa",
	statusline3 = "#e67e80",

	-- neutral backgrounds (dark -> light)
	bg_dim = "#272f35",
	bg0 = "#2b3339",
	bg1 = "#323c41",
	bg2 = "#3a4248",
	bg3 = "#424a50",
	bg4 = "#4a5258",
	bg5 = "#4e565c",

	-- hue-tinted backgrounds (diff lines, inline highlights, visual selection)
	bg_visual = "#4c3743",
	bg_red = "#452132",
	bg_green = "#213c45",
	bg_blue = "#212d45",
	bg_yellow = "#453a21",
	bg_purple = "#3e2145",
}
